import type { Category, PopularService } from "./types"
import {
  Tv,
  Dumbbell,
  Music,
  ShoppingBag,
  Smartphone,
  Cloud,
  Newspaper,
  Coffee,
  Utensils,
  BookOpen,
  Tag,
} from "lucide-react"

export const defaultCategories: Category[] = [
  {
    id: "streaming",
    name: "Streaming",
    icon: "Tv",
    color: "bg-purple-500",
  },
  {
    id: "fitness",
    name: "Fitness",
    icon: "Dumbbell",
    color: "bg-green-500",
  },
  {
    id: "music",
    name: "Music",
    icon: "Music",
    color: "bg-pink-500",
  },
  {
    id: "shopping",
    name: "Shopping",
    icon: "ShoppingBag",
    color: "bg-blue-500",
  },
  {
    id: "apps",
    name: "Apps",
    icon: "Smartphone",
    color: "bg-orange-500",
  },
  {
    id: "cloud",
    name: "Cloud Storage",
    icon: "Cloud",
    color: "bg-sky-500",
  },
  {
    id: "news",
    name: "News",
    icon: "Newspaper",
    color: "bg-red-500",
  },
  {
    id: "food",
    name: "Food & Drink",
    icon: "Coffee",
    color: "bg-amber-500",
  },
  {
    id: "dining",
    name: "Dining",
    icon: "Utensils",
    color: "bg-emerald-500",
  },
  {
    id: "education",
    name: "Education",
    icon: "BookOpen",
    color: "bg-indigo-500",
  },
  {
    id: "other",
    name: "Other",
    icon: "Tag",
    color: "bg-gray-500",
  },
]

export const popularServices: PopularService[] = [
  // Global Streaming Services
  {
    name: "Netflix",
    categoryId: "streaming",
    monthlyCost: 15.49, // Base USD price
    description: "Standard Plan (HD)",
    logoUrl: "/netflix-inspired-logo.png",
    availability: [
      "US",
      "CA",
      "GB",
      "AU",
      "DE",
      "FR",
      "IT",
      "ES",
      "NL",
      "JP",
      "KR",
      "IN",
      "BR",
      "MX",
      "SE",
      "NO",
      "DK",
      "CH",
      "PL",
      "CZ",
      "HU",
      "RO",
      "BG",
    ],
  },
  {
    name: "Disney+",
    categoryId: "streaming",
    monthlyCost: 7.99,
    description: "Basic Plan",
    logoUrl: "/disney-plus-logo.png",
    availability: [
      "US",
      "CA",
      "GB",
      "AU",
      "DE",
      "FR",
      "IT",
      "ES",
      "NL",
      "JP",
      "KR",
      "IN",
      "BR",
      "SE",
      "NO",
      "DK",
      "CH",
      "PL",
      "CZ",
      "HU",
      "RO",
      "BG",
    ],
  },
  {
    name: "Amazon Prime Video",
    categoryId: "streaming",
    monthlyCost: 8.99,
    description: "Video only",
    logoUrl: "/amazon-prime-video-logo.png",
    availability: [
      "US",
      "CA",
      "GB",
      "AU",
      "DE",
      "FR",
      "IT",
      "ES",
      "NL",
      "JP",
      "KR",
      "IN",
      "BR",
      "MX",
      "SE",
      "NO",
      "DK",
      "CH",
      "PL",
      "CZ",
      "HU",
      "RO",
      "BG",
    ],
  },
  {
    name: "Apple TV+",
    categoryId: "streaming",
    monthlyCost: 6.99,
    description: "Standard Plan",
    logoUrl: "/apple-tv-plus-logo.png",
    availability: [
      "US",
      "CA",
      "GB",
      "AU",
      "DE",
      "FR",
      "IT",
      "ES",
      "NL",
      "JP",
      "KR",
      "IN",
      "BR",
      "MX",
      "SE",
      "NO",
      "DK",
      "CH",
      "PL",
      "CZ",
      "HU",
      "RO",
      "BG",
    ],
  },
  {
    name: "Paramount+",
    categoryId: "streaming",
    monthlyCost: 5.99,
    description: "Essential Plan",
    logoUrl: "/paramount-plus-logo.png",
    availability: [
      "US",
      "CA",
      "GB",
      "AU",
      "DE",
      "FR",
      "IT",
      "ES",
      "NL",
      "KR",
      "IN",
      "BR",
      "MX",
      "SE",
      "NO",
      "DK",
      "CH",
    ],
  },

  // Australia-Specific Services
  {
    name: "Stan",
    categoryId: "streaming",
    monthlyCost: 10.0, // AUD 10/month base price
    description: "Standard Plan",
    availability: ["AU"],
  },
  {
    name: "Foxtel Now",
    categoryId: "streaming",
    monthlyCost: 25.0, // AUD 25/month base price
    description: "Entertainment Pack",
    availability: ["AU"],
  },
  {
    name: "Binge",
    categoryId: "streaming",
    monthlyCost: 10.0, // AUD 10/month
    description: "Standard Plan",
    availability: ["AU"],
  },
  {
    name: "Kayo Sports",
    categoryId: "streaming",
    monthlyCost: 25.0, // AUD 25/month
    description: "Basic Plan",
    availability: ["AU"],
  },
  {
    name: "ABC iview",
    categoryId: "streaming",
    monthlyCost: 0.0, // Free
    description: "Free with ads",
    availability: ["AU"],
  },
  {
    name: "SBS On Demand",
    categoryId: "streaming",
    monthlyCost: 0.0, // Free
    description: "Free with ads",
    availability: ["AU"],
  },
  {
    name: "7plus",
    categoryId: "streaming",
    monthlyCost: 0.0, // Free
    description: "Free with ads",
    availability: ["AU"],
  },
  {
    name: "9Now",
    categoryId: "streaming",
    monthlyCost: 0.0, // Free
    description: "Free with ads",
    availability: ["AU"],
  },
  {
    name: "10 play",
    categoryId: "streaming",
    monthlyCost: 0.0, // Free
    description: "Free with ads",
    availability: ["AU"],
  },

  // US-Specific Services
  {
    name: "Hulu",
    categoryId: "streaming",
    monthlyCost: 7.99,
    description: "With Ads",
    logoUrl: "/hulu-logo.png",
    availability: ["US"],
  },
  {
    name: "HBO Max",
    categoryId: "streaming",
    monthlyCost: 15.99,
    description: "Ad-Free",
    logoUrl: "/hbo-max-logo.png",
    availability: ["US", "CA", "MX", "BR", "AR"],
  },
  {
    name: "Peacock",
    categoryId: "streaming",
    monthlyCost: 5.99,
    description: "Premium Plan",
    logoUrl: "/peacock-logo.png",
    availability: ["US"],
  },

  // UK-Specific Services
  {
    name: "BBC iPlayer",
    categoryId: "streaming",
    monthlyCost: 0.0, // Free (with TV license)
    description: "Free with TV License",
    availability: ["GB"],
  },
  {
    name: "ITV Hub",
    categoryId: "streaming",
    monthlyCost: 0.0, // Free
    description: "Free with ads",
    availability: ["GB"],
  },
  {
    name: "All 4",
    categoryId: "streaming",
    monthlyCost: 0.0, // Free
    description: "Free with ads",
    availability: ["GB"],
  },
  {
    name: "My5",
    categoryId: "streaming",
    monthlyCost: 0.0, // Free
    description: "Free with ads",
    availability: ["GB"],
  },
  {
    name: "Sky Go",
    categoryId: "streaming",
    monthlyCost: 25.0, // Approximate GBP
    description: "Entertainment Package",
    availability: ["GB"],
  },
  {
    name: "NOW TV",
    categoryId: "streaming",
    monthlyCost: 9.99, // GBP
    description: "Entertainment Pass",
    availability: ["GB"],
  },

  // Canada-Specific Services
  {
    name: "Crave",
    categoryId: "streaming",
    monthlyCost: 9.99, // CAD
    description: "Basic Plan",
    availability: ["CA"],
  },
  {
    name: "CBC Gem",
    categoryId: "streaming",
    monthlyCost: 0.0, // Free
    description: "Free with ads",
    availability: ["CA"],
  },

  // Germany-Specific Services
  {
    name: "RTL+",
    categoryId: "streaming",
    monthlyCost: 4.99, // EUR
    description: "Premium",
    availability: ["DE"],
  },
  {
    name: "Joyn PLUS+",
    categoryId: "streaming",
    monthlyCost: 6.99, // EUR
    description: "Premium",
    availability: ["DE"],
  },

  // France-Specific Services
  {
    name: "Canal+",
    categoryId: "streaming",
    monthlyCost: 20.99, // EUR
    description: "Standard",
    availability: ["FR"],
  },
  {
    name: "France.tv",
    categoryId: "streaming",
    monthlyCost: 0.0, // Free
    description: "Free",
    availability: ["FR"],
  },

  // Japan-Specific Services
  {
    name: "Hulu Japan",
    categoryId: "streaming",
    monthlyCost: 7.99, // USD equivalent
    description: "Standard Plan",
    availability: ["JP"],
  },
  {
    name: "U-NEXT",
    categoryId: "streaming",
    monthlyCost: 15.0, // USD equivalent
    description: "Monthly Plan",
    availability: ["JP"],
  },
  {
    name: "AbemaTV",
    categoryId: "streaming",
    monthlyCost: 0.0, // Free tier
    description: "Free with ads",
    availability: ["JP"],
  },

  // India-Specific Services
  {
    name: "Hotstar",
    categoryId: "streaming",
    monthlyCost: 3.0, // USD equivalent
    description: "Premium",
    availability: ["IN"],
  },
  {
    name: "SonyLIV",
    categoryId: "streaming",
    monthlyCost: 2.5, // USD equivalent
    description: "Premium",
    availability: ["IN"],
  },
  {
    name: "Zee5",
    categoryId: "streaming",
    monthlyCost: 2.0, // USD equivalent
    description: "Premium",
    availability: ["IN"],
  },

  // Music Services (Global)
  {
    name: "Spotify",
    categoryId: "music",
    monthlyCost: 9.99,
    description: "Individual Plan",
    availability: [
      "US",
      "CA",
      "GB",
      "AU",
      "DE",
      "FR",
      "IT",
      "ES",
      "NL",
      "JP",
      "KR",
      "IN",
      "BR",
      "MX",
      "SE",
      "NO",
      "DK",
      "CH",
      "PL",
      "CZ",
      "HU",
      "RO",
      "BG",
    ],
  },
  {
    name: "Apple Music",
    categoryId: "music",
    monthlyCost: 10.99,
    description: "Individual Plan",
    availability: [
      "US",
      "CA",
      "GB",
      "AU",
      "DE",
      "FR",
      "IT",
      "ES",
      "NL",
      "JP",
      "KR",
      "IN",
      "BR",
      "MX",
      "SE",
      "NO",
      "DK",
      "CH",
      "PL",
      "CZ",
      "HU",
      "RO",
      "BG",
    ],
  },
  {
    name: "YouTube Premium",
    categoryId: "music",
    monthlyCost: 11.99,
    description: "Individual Plan",
    availability: [
      "US",
      "CA",
      "GB",
      "AU",
      "DE",
      "FR",
      "IT",
      "ES",
      "NL",
      "JP",
      "KR",
      "IN",
      "BR",
      "MX",
      "SE",
      "NO",
      "DK",
      "CH",
      "PL",
      "CZ",
      "HU",
      "RO",
      "BG",
    ],
  },

  // Other Services
  {
    name: "Planet Fitness",
    categoryId: "fitness",
    monthlyCost: 10.0,
    description: "Basic Membership",
    availability: ["US"],
  },
  {
    name: "LA Fitness",
    categoryId: "fitness",
    monthlyCost: 29.99,
    description: "Single Club Access",
    availability: ["US"],
  },
  {
    name: "Peloton",
    categoryId: "fitness",
    monthlyCost: 12.99,
    description: "App Membership",
    availability: ["US", "CA", "GB", "AU", "DE"],
  },
  {
    name: "Amazon Prime",
    categoryId: "shopping",
    monthlyCost: 14.99,
    description: "Monthly Membership",
    availability: ["US", "CA", "GB", "AU", "DE", "FR", "IT", "ES", "JP", "IN"],
  },
  {
    name: "Instacart+",
    categoryId: "shopping",
    monthlyCost: 9.99,
    description: "Monthly Membership",
    availability: ["US", "CA"],
  },
  {
    name: "iCloud+",
    categoryId: "cloud",
    monthlyCost: 2.99,
    description: "50GB Storage",
    availability: [
      "US",
      "CA",
      "GB",
      "AU",
      "DE",
      "FR",
      "IT",
      "ES",
      "NL",
      "JP",
      "KR",
      "IN",
      "BR",
      "MX",
      "SE",
      "NO",
      "DK",
      "CH",
      "PL",
      "CZ",
      "HU",
      "RO",
      "BG",
    ],
  },
  {
    name: "Google One",
    categoryId: "cloud",
    monthlyCost: 1.99,
    description: "100GB Storage",
    availability: [
      "US",
      "CA",
      "GB",
      "AU",
      "DE",
      "FR",
      "IT",
      "ES",
      "NL",
      "JP",
      "KR",
      "IN",
      "BR",
      "MX",
      "SE",
      "NO",
      "DK",
      "CH",
      "PL",
      "CZ",
      "HU",
      "RO",
      "BG",
    ],
  },
  {
    name: "Dropbox",
    categoryId: "cloud",
    monthlyCost: 11.99,
    description: "Plus Plan",
    availability: [
      "US",
      "CA",
      "GB",
      "AU",
      "DE",
      "FR",
      "IT",
      "ES",
      "NL",
      "JP",
      "KR",
      "IN",
      "BR",
      "MX",
      "SE",
      "NO",
      "DK",
      "CH",
      "PL",
      "CZ",
      "HU",
      "RO",
      "BG",
    ],
  },
  {
    name: "New York Times",
    categoryId: "news",
    monthlyCost: 4.25,
    description: "Basic Digital Access",
    availability: ["US", "CA", "GB", "AU"],
  },
  {
    name: "Washington Post",
    categoryId: "news",
    monthlyCost: 4.0,
    description: "Digital Access",
    availability: ["US", "CA", "GB", "AU"],
  },
  {
    name: "ChatGPT Plus",
    categoryId: "apps",
    monthlyCost: 20.0,
    description: "Premium Access",
    availability: [
      "US",
      "CA",
      "GB",
      "AU",
      "DE",
      "FR",
      "IT",
      "ES",
      "NL",
      "JP",
      "KR",
      "IN",
      "BR",
      "MX",
      "SE",
      "NO",
      "DK",
      "CH",
      "PL",
      "CZ",
      "HU",
      "RO",
      "BG",
    ],
  },
  {
    name: "Adobe Creative Cloud",
    categoryId: "apps",
    monthlyCost: 54.99,
    description: "All Apps Plan",
    availability: [
      "US",
      "CA",
      "GB",
      "AU",
      "DE",
      "FR",
      "IT",
      "ES",
      "NL",
      "JP",
      "KR",
      "IN",
      "BR",
      "MX",
      "SE",
      "NO",
      "DK",
      "CH",
      "PL",
      "CZ",
      "HU",
      "RO",
      "BG",
    ],
  },
  {
    name: "Microsoft 365",
    categoryId: "apps",
    monthlyCost: 6.99,
    description: "Personal Plan",
    availability: [
      "US",
      "CA",
      "GB",
      "AU",
      "DE",
      "FR",
      "IT",
      "ES",
      "NL",
      "JP",
      "KR",
      "IN",
      "BR",
      "MX",
      "SE",
      "NO",
      "DK",
      "CH",
      "PL",
      "CZ",
      "HU",
      "RO",
      "BG",
    ],
  },
]

export function getCategoryIcon(iconName: string) {
  switch (iconName) {
    case "Tv":
      return Tv
    case "Dumbbell":
      return Dumbbell
    case "Music":
      return Music
    case "ShoppingBag":
      return ShoppingBag
    case "Smartphone":
      return Smartphone
    case "Cloud":
      return Cloud
    case "Newspaper":
      return Newspaper
    case "Coffee":
      return Coffee
    case "Utensils":
      return Utensils
    case "BookOpen":
      return BookOpen
    case "Tag":
    default:
      return Tag
  }
}
